"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Check, Github, Link2, Menu, PenLine, Plus, X, Eye, LockKeyhole } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { ConnectMockup, CredentialsMockup, ExperienceMockup, FinalProjectFragment, HeatmapMockup, HeroPortfolioPreview, ProjectMockup } from "./ProductMockups";

const nav = [{ label: "Product", href: "#product" }, { label: "How It Works", href: "#how-it-works" }, { label: "FAQ", href: "#faq" }, { label: "See It Live", href: "/user/Jigar18" }];
const steps = [
  ["01", Github, "Connect GitHub", "Sign in using the account where your work already lives."],
  ["02", Link2, "Connect repositories", "Install the GitHub App for repository access and contribution data."],
  ["03", PenLine, "Set the foundation", "Add your role, location, education, skills, and profile picture."],
  ["04", ArrowRight, "Publish and keep building", "Share your public link, then add projects, experience, credentials, and contact links."],
] as const;
const faqs = [["What comes from GitHub?", "Your GitHub identity and contribution activity are connected. You choose the projects to feature and write their story."], ["Do private repositories appear automatically?", "No. Repositories only become part of your public portfolio when you choose to present them."], ["Do I need to code anything?", "No. Guided forms and owner controls handle the portfolio content."], ["Can I update it later?", "Yes. You can continue editing your portfolio as your projects, skills, and experience grow."], ["What do visitors see?", "Visitors see the content you publish—not your editing controls or account actions."]];

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <motion.div {...{ className }} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .45, ease: [0.22, 1, .36, 1] }}>{children}</motion.div> }
function Logo() { return <span className="flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-lg border border-white/20 bg-zinc-200 font-mono text-sm font-bold text-zinc-950">B</span><span className="text-sm font-semibold tracking-tight">Byldit</span></span> }
function CTA({ children = "Build Mine with GitHub", className = "" }: { children?: React.ReactNode; className?: string }) { return <a href="/api/github/auth" className={`group inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-zinc-100 px-5 text-sm font-semibold text-zinc-950 transition duration-200 hover:-translate-y-0.5 hover:bg-white focus:outline-none focus:ring-2 focus:ring-zinc-300 focus:ring-offset-2 focus:ring-offset-[#09090B] ${className}`}>{children}<ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5"/></a> }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[10px] uppercase tracking-[.22em] text-zinc-500">{children}</p> }
function Feature({ number, title, copy, visual, reverse = false }: { number: string; title: string; copy: string; visual: React.ReactNode; reverse?: boolean }) { return <Reveal className={`grid items-center gap-10 border-t border-white/[.08] py-20 lg:grid-cols-2 lg:gap-20 ${reverse ? "lg:[&>*:first-child]:order-2" : ""}`}><div><Eyebrow>{number} / FEATURE</Eyebrow><h3 className="mt-5 max-w-lg text-3xl font-semibold leading-tight tracking-[-.04em] text-zinc-100 sm:text-4xl">{title}</h3><p className="mt-5 max-w-lg text-base leading-7 text-zinc-400">{copy}</p></div><div className="min-w-0">{visual}</div></Reveal> }

export default function LandingPage() {
  const heroRef = useRef<HTMLElement>(null); const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 24); fn(); window.addEventListener("scroll", fn, { passive: true }); return () => window.removeEventListener("scroll", fn) }, []);
  return <main className="min-h-screen overflow-hidden bg-[#09090B] text-zinc-100 selection:bg-zinc-100 selection:text-zinc-950">
    <header className={`fixed inset-x-0 top-0 z-50 border-b transition duration-200 ${scrolled || open ? "border-white/[.08] bg-[#09090B]/90 backdrop-blur-xl" : "border-transparent bg-[#09090B]/70"}`}><nav className="mx-auto flex h-[4.5rem] max-w-7xl items-center px-5 sm:px-8 lg:px-10"><Link href="/" aria-label="Byldit home"><Logo/></Link><div className="ml-auto hidden items-center gap-7 lg:flex">{nav.map(x => x.href.startsWith("#") ? <a key={x.label} href={x.href} className="text-xs text-zinc-400 transition hover:text-white">{x.label}</a> : <Link key={x.label} href={x.href} className="text-xs text-zinc-400 transition hover:text-white">{x.label}</Link>)}</div><div className="ml-8 hidden items-center gap-4 sm:flex"><Link href="/login" className="text-xs text-zinc-300 hover:text-white">Log In</Link><a href="/api/github/auth" className="inline-flex min-h-10 items-center rounded-lg bg-zinc-100 px-4 text-xs font-semibold text-zinc-950 hover:bg-white">Build Yours</a></div><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? "Close navigation" : "Open navigation"} className="ml-auto grid size-11 place-items-center rounded-lg border border-white/10 sm:hidden">{open ? <X className="size-4"/> : <Menu className="size-4"/>}</button></nav>{open && <div className="border-t border-white/[.08] bg-[#09090B] px-5 py-4 sm:hidden"><div className="grid gap-1">{nav.map(x => x.href.startsWith("#") ? <a key={x.label} href={x.href} onClick={() => setOpen(false)} className="min-h-11 border-b border-white/[.06] py-3 text-sm text-zinc-300">{x.label}</a> : <Link key={x.label} href={x.href} onClick={() => setOpen(false)} className="min-h-11 border-b border-white/[.06] py-3 text-sm text-zinc-300">{x.label}</Link>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><Link href="/login" className="grid min-h-11 place-items-center rounded-lg border border-white/15 text-sm">Log In</Link><a href="/api/github/auth" className="grid min-h-11 place-items-center rounded-lg bg-zinc-100 text-sm font-semibold text-zinc-950">Build Yours</a></div></div>}</header>
    <section ref={heroRef} className="mx-auto grid min-h-[46rem] max-w-7xl items-center gap-12 px-5 pb-20 pt-28 sm:px-8 lg:grid-cols-[.82fr_1.18fr] lg:px-10 lg:pb-24"><Reveal className="relative z-10"><Eyebrow>Built from your GitHub. Finished by you.</Eyebrow><h1 className="mt-6 max-w-xl text-[2.7rem] font-semibold leading-[.98] tracking-[-.06em] text-zinc-50 sm:text-[4.2rem]">Your GitHub shows the code.<br/><span className="text-zinc-500">Your portfolio tells the story.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-zinc-400 sm:text-lg">Bring your projects, contributions, skills, and experience into one link that shows what you can actually do.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><CTA/><Link href="/user/Jigar18" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-white/15 px-5 text-sm font-medium text-zinc-300 transition hover:border-white/30 hover:text-white">See a Live Portfolio<ArrowRight className="size-4"/></Link></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 font-mono text-[9px] uppercase tracking-[.14em] text-zinc-600">{["Guided setup", "No code required", "One link to share"].map(x => <span key={x} className="flex items-center gap-2"><Check className="size-3 text-zinc-400"/>{x}</span>)}</div></Reveal><Reveal className="relative z-10 min-w-0 lg:pt-10"><HeroPortfolioPreview/></Reveal></section>
    <section id="product" className="scroll-mt-20 border-y border-white/[.08] bg-[#0C0C0E] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal><Eyebrow>See the result</Eyebrow><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">This is what “done” looks like.</h2><p className="mt-5 max-w-xl text-base leading-7 text-zinc-400">One focused page for the work, proof, and experience people came to see.</p></Reveal><Reveal className="mt-12"><HeroPortfolioPreview/></Reveal><div className="mt-8 grid gap-3 border-t border-white/[.08] pt-6 sm:grid-cols-3 lg:grid-cols-6">{["Profile and story", "Projects and demos", "GitHub contributions", "Experience and skills", "Education and certifications", "Contact links"].map(x => <span key={x} className="font-mono text-[9px] uppercase leading-4 tracking-[.12em] text-zinc-600">{x}</span>)}</div></div></section>
    <section id="features" className="scroll-mt-20 px-5 sm:px-8"><div className="mx-auto max-w-7xl"><Reveal className="py-24 lg:py-32"><Eyebrow>01 / PRODUCT BENEFITS</Eyebrow><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Show the work. Skip the résumé PDF.</h2><p className="mt-5 max-w-xl text-base leading-7 text-zinc-400">Turn repository links, job titles, and credentials into proof people can actually explore.</p></Reveal><Feature number="02.1" title="Projects, with the why." copy="Add the story, stack, repository, live link, and demo behind what you shipped." visual={<ProjectMockup/>}/><Feature number="02.2" title="Proof that keeps moving." copy="Your GitHub contribution heatmap stays connected, so your portfolio does not freeze when you publish it." visual={<HeatmapMockup/>} reverse/><Feature number="02.3" title="More than code." copy="Bring your experience, skills, education, certifications, and ways to reach you into the same story." visual={<div className="grid gap-3 sm:grid-cols-2"><ExperienceMockup/><CredentialsMockup/></div>}/></div></section>
    <section className="border-y border-white/[.08] bg-[#0C0C0E] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal><Eyebrow>Yours to keep shaping</Eyebrow><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">It grows when you do.</h2><p className="mt-5 max-w-xl text-base leading-7 text-zinc-400">Update your portfolio as your work changes—no code, no rebuild, no starting over.</p></Reveal><div className="mt-14"><ConnectMockup/></div></div></section>
    <section id="how-it-works" className="scroll-mt-20 px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal><Eyebrow>Four steps. No guesswork.</Eyebrow><h2 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">From GitHub to live.</h2><p className="mt-5 max-w-xl text-base leading-7 text-zinc-400">Follow the guided setup once, then keep refining your portfolio whenever your work changes.</p></Reveal><div className="mt-14 grid border border-white/[.08] md:grid-cols-4">{steps.map(([n, Icon, title, copy]) => <Reveal key={n} className="border-b border-white/[.08] p-6 last:border-0 md:border-b-0 md:border-r md:last:border-0"><div className="flex items-center justify-between"><Icon className="size-5 text-zinc-400"/><span className="font-mono text-[10px] text-zinc-600">{n}</span></div><h3 className="mt-12 text-lg font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{copy}</p></Reveal>)}</div></div></section>
    <section id="faq" className="scroll-mt-20 border-t border-white/[.08] bg-[#0C0C0E] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-3xl"><Reveal><Eyebrow>FAQ</Eyebrow><h2 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Good to know.</h2></Reveal><div className="mt-12 divide-y divide-white/[.08] border-y border-white/[.08]">{faqs.map(([question, answer]) => <details key={question} className="group"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 text-sm font-medium text-zinc-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 [&::-webkit-details-marker]:hidden">{question}<Plus className="size-4 shrink-0 text-zinc-500 transition group-open:rotate-45"/></summary><p className="max-w-2xl pb-6 pr-8 text-sm leading-6 text-zinc-500">{answer}</p></details>)}</div></div></section>
    <section className="relative overflow-hidden px-5 py-28 sm:px-8 lg:py-40"><FinalProjectFragment/><Reveal className="relative mx-auto max-w-3xl"><Eyebrow>Ready when your work is</Eyebrow><h2 className="mt-5 max-w-2xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Stop explaining your work. Show it.</h2><p className="mt-5 max-w-xl text-base leading-7 text-zinc-400">Bring the proof, progress, and story together—and share one link that does them justice.</p><CTA className="mt-8"/></Reveal></section>
    <footer className="border-t border-white/[.08] bg-[#0C0C0E] px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-10 md:flex-row md:items-start md:justify-between"><div><Link href="/"><Logo/></Link><p className="mt-4 max-w-xs text-sm leading-6 text-zinc-600">One home for the work behind the developer.</p></div><div className="grid grid-cols-2 gap-x-10 gap-y-4 text-xs text-zinc-500 sm:grid-cols-3"><a href="#product" className="hover:text-white">Product</a><a href="#how-it-works" className="hover:text-white">How It Works</a><a href="#faq" className="hover:text-white">FAQ</a><Link href="/user/Jigar18" className="hover:text-white">Live Portfolio</Link><a href="https://github.com/Jigar18/Portfolio-Creator" className="hover:text-white">GitHub Repository</a><Link href="/login" className="hover:text-white">Log In</Link></div></div><div className="mt-12 flex flex-col gap-3 border-t border-white/[.08] pt-6 font-mono text-[9px] uppercase tracking-[.14em] text-zinc-700 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} Byldit</span><span>Built for the work behind the developer.</span></div></div></footer>
  </main>
}
