import { Award, BarChart3, BriefcaseBusiness, Check, Eye, ExternalLink, Github, GraduationCap, LockKeyhole, MapPin, Pencil, Play, Settings2, ShieldCheck, ToggleRight, Users } from "lucide-react";

const heatmap = Array.from({ length: 140 }, (_, index) => index % 17 === 0 ? 4 : index % 9 === 0 ? 3 : index % 4 === 0 ? 2 : index % 3 === 0 ? 1 : 0);
const heat = ["bg-white/[0.04]", "bg-zinc-700", "bg-zinc-500", "bg-zinc-300", "bg-zinc-100"];

function BrowserFrame({ children, label = "byldit.dev/mark" }: { children: React.ReactNode; label?: string }) {
  return <div className="overflow-hidden rounded-xl border border-white/10 bg-[#111113] shadow-[0_24px_80px_-40px_rgba(0,0,0,.9)]">
    <div className="flex h-9 items-center gap-3 border-b border-white/[0.08] bg-[#18181B] px-4"><div className="flex gap-1.5"><i className="size-2 rounded-full bg-zinc-600"/><i className="size-2 rounded-full bg-zinc-600"/><i className="size-2 rounded-full bg-zinc-600"/></div><div className="flex h-5 flex-1 items-center rounded-md border border-white/[0.06] px-2 font-mono text-[9px] text-zinc-500">{label}</div></div>{children}
  </div>
}

function HeatmapGrid() { return <div className="grid grid-flow-col grid-rows-7 gap-1" aria-label="GitHub contribution activity">{heatmap.map((level, i) => <span key={i} className={`aspect-square rounded-[2px] ${heat[level]}`} />)}</div> }

function ProjectCard({ name, description, stack }: { name: string; description: string; stack: string[] }) { return <article className="rounded-lg border border-white/[0.08] bg-[#18181B] p-4 transition-transform duration-200 hover:-translate-y-0.5"><div className="flex h-20 items-end rounded-md border border-white/[0.06] bg-[#27272A] p-3"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-400">{name} / case study</span></div><div className="mt-4 flex items-start justify-between gap-3"><div><h4 className="font-medium text-zinc-100">{name}</h4><p className="mt-1 text-[11px] leading-5 text-zinc-500">{description}</p></div><ExternalLink className="size-3.5 shrink-0 text-zinc-500"/></div><div className="mt-4 flex flex-wrap gap-1.5">{stack.map((item) => <span key={item} className="rounded-full border border-white/[0.08] px-2 py-1 font-mono text-[8px] text-zinc-400">{item}</span>)}</div></article> }

function PortfolioContent({ compact = false }: { compact?: boolean }) { return <div className={`relative bg-[#09090B] p-5 text-zinc-100 sm:p-7 ${compact ? "" : "min-h-[42rem]"}`}>
  <div className="flex items-start justify-between gap-5"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-full border border-white/10 bg-[#27272A] font-serif text-lg text-zinc-200">M</div><div><p className="text-sm font-semibold">Mark</p><p className="mt-1 text-[10px] text-zinc-500">Senior Software Developer</p><p className="mt-1 flex items-center gap-1 font-mono text-[8px] text-zinc-600"><MapPin className="size-3"/>Earth, Milky Way · Google</p></div></div><span className="rounded-full border border-white/10 px-2 py-1 font-mono text-[8px] text-zinc-500">available</span></div>
  <div className="mt-7 max-w-2xl"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600">About</p><p className="mt-3 text-sm leading-6 text-zinc-400">I build reliable developer tools and distributed systems that make complex workflows feel simple. I care about clear architecture, thoughtful interfaces, and software that stays maintainable as it grows.</p></div>
  {!compact && <><div className="mt-8 flex items-center justify-between border-b border-white/[0.08] pb-3"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600">Selected work</p><span className="text-[10px] text-zinc-500">02 projects</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><ProjectCard name="Orbit" description="An observability workspace that makes distributed systems easier to understand and operate." stack={["TypeScript", "Next.js", "OpenTelemetry"]}/><ProjectCard name="Relay" description="A collaborative API workspace for designing, testing, and reviewing service contracts." stack={["React", "Node.js", "PostgreSQL"]}/></div><div className="mt-8 border-t border-white/[0.08] pt-5"><div className="flex items-center justify-between"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600">GitHub contributions</p><span className="font-mono text-[8px] text-zinc-600">843 this year</span></div><div className="mt-4 overflow-hidden"><HeatmapGrid/></div></div><div className="mt-7 grid gap-4 border-t border-white/[0.08] pt-5 sm:grid-cols-2"><Timeline/><Credentials/></div></>}
  <div className="pointer-events-none absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-[#09090B] via-[#09090B]/85 to-transparent backdrop-blur-[2px]" />
</div> }

function Timeline() { return <div><p className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600"><BriefcaseBusiness className="size-3.5"/> Experience</p><div className="mt-4 border-l border-white/10 pl-4"><p className="text-xs font-medium">Senior Software Developer</p><p className="mt-1 text-[10px] text-zinc-500">Google · 2024—Now</p><p className="mt-2 text-[10px] leading-4 text-zinc-600">Led platform modernization across shared services.</p></div></div> }
function Credentials() { return <div><p className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600"><Award className="size-3.5"/> Credentials</p><div className="mt-4 grid gap-3 text-[10px] text-zinc-400"><p className="flex gap-2"><GraduationCap className="size-3.5 text-zinc-500"/>B.S. Computer Science, Stanford</p><p className="flex gap-2"><ShieldCheck className="size-3.5 text-zinc-500"/>Cloud Architect certified</p></div></div> }

export function HeroPortfolioPreview() { return <div className="mx-auto w-full max-w-2xl"><BrowserFrame><PortfolioContent/></BrowserFrame><p className="mt-3 text-center font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600">A living portfolio, not a static résumé</p></div> }
export function ProjectMockup() { return <div className="grid gap-3 sm:grid-cols-2"><ProjectCard name="Orbit" description="An observability workspace that makes distributed systems easier to understand and operate." stack={["TypeScript", "Next.js", "OpenTelemetry"]}/><ProjectCard name="Relay" description="A collaborative API workspace for designing, testing, and reviewing service contracts." stack={["React", "Node.js", "PostgreSQL"]}/></div> }
export function HeatmapMockup() { return <div className="rounded-xl border border-white/10 bg-[#111113] p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Github className="size-5 text-zinc-300"/><div><p className="text-sm font-medium">GitHub contributions</p><p className="mt-1 font-mono text-[9px] text-zinc-600">Connected activity · 843 contributions</p></div></div><BarChart3 className="size-4 text-zinc-500"/></div><div className="mt-8 overflow-hidden"><HeatmapGrid/></div><div className="mt-5 flex justify-between font-mono text-[8px] text-zinc-600"><span>Less</span><span>More</span></div></div> }
export function CredentialsMockup() { return <div className="rounded-xl border border-white/10 bg-[#111113] p-6"><Credentials/><div className="mt-7 flex flex-wrap gap-2">{["TypeScript","React","Next.js","Node.js","Java","Spring Boot","PostgreSQL","Kubernetes"].map(x=><span key={x} className="rounded-full border border-white/10 px-2.5 py-1 font-mono text-[9px] text-zinc-400">{x}</span>)}</div></div> }
export function ExperienceMockup() { return <div className="rounded-xl border border-white/10 bg-[#111113] p-6"><Timeline/><div className="mt-6 border-t border-white/[0.08] pt-5"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-600">Contributions</p><ul className="mt-3 grid gap-2 text-xs text-zinc-400"><li className="flex gap-2"><Check className="size-3.5 text-zinc-500"/>Led platform modernization across shared services.</li><li className="flex gap-2"><Check className="size-3.5 text-zinc-500"/>Built observability workflows for releases.</li></ul></div></div> }
export function ConnectMockup() { return <div className="grid gap-2 sm:grid-cols-3"><OwnershipControl icon={Pencil} label="Edit where it lives" value="Owner controls"/><OwnershipControl icon={ToggleRight} label="Show what matters" value="Heatmap visible"/><OwnershipControl icon={Users} label="See the reach" value="128 unique views"/></div> }
export function OwnershipControl({ icon: Icon, label, value }: { icon: typeof Pencil; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-lg border border-white/10 bg-[#111113] p-4"><Icon className="size-4 text-zinc-400"/><div><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-zinc-600">{label}</p><p className="mt-1 text-xs text-zinc-300">{value}</p></div></div> }
export function FinalProjectFragment() { return <div className="absolute -right-16 top-10 hidden w-80 rotate-6 opacity-25 sm:block"><BrowserFrame><PortfolioContent compact/></BrowserFrame></div> }
export { LockKeyhole, Eye };
